### ISSUE TITLE
Crashing when trying to load an sp world

### ISSUE THREAD

**Issue by WickedSchnitzel** [FatigueDev/typing_indicator#1]
Running on 64 bit Windows 10.0.19045.0 with 32723 MB RAM
Game Version: v1.19.8 (Stable)
27.06.2024 08:02:56: Critical error occurred in the following mod: typing_indicator@1.1.0
Loaded Mods: ClaimsRadar@1.1.0, game@1.19.8, worldgenfix@1.3.0, extrainfo@1.7.0, decayingcreatures@0.0.3, furniturelibrary@1.0.11, rivers@3.1.0, typing_indicator@1.1.0, creative@1.19.8, survival@1.19.8, cob2@1.6.4, cobserver@1.0.1, pomdrafts@1.0.0, cob@1.9.2
System.NullReferenceException: Object reference not set to an instance of an object.
   at TypingIndicator.EntityBehaviorTypingIndicator.TryGetChatGUI(ICoreClientAPI clapi) in /run/media/fatigue/hdd/Projects/typing_indicator/TypingIndicator/EntityBehaviorTypingIndicator.cs:line 183
   at TypingIndicator.EntityBehaviorTypingIndicator.OnGameTick(Single deltaTime) in /run/media/fatigue/hdd/Projects/typing_indicator/TypingIndicator/EntityBehaviorTypingIndicator.cs:line 199
   at Vintagestory.API.Common.Entities.Entity.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\Entity.cs:line 896
   at Vintagestory.API.Common.EntityAgent.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\EntityAgent.cs:line 539
   at Vintagestory.API.Common.EntityPlayer.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 678
   at Vintagestory.Client.NoObf.ClientSystemEntities.OnGameTick(Single dt) in VintagestoryLib\Client\Systems\Entities.cs:line 95
   at Vintagestory.Common.GameTickListener.OnTriggered(Int64 ellapsedMilliseconds) in VintagestoryLib\Common\Model\GameTickListener.cs:line 19
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 81
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 838
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 730
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 19.06.2024 15:21:31, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.8.0, Zeitstempel: 0x661e0000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x6b8c
Startzeit der fehlerhaften Anwendung: 0x01dac24b7454aef3
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Kai\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: d42dce8f-e937-463d-bdf1-dc1ca8d2cb67
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 19.06.2024 15:11:27, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.8.0, Zeitstempel: 0x661e0000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x4a98
Startzeit der fehlerhaften Anwendung: 0x01dac24a14f1d3a4
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Kai\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: 36e8b460-f4ea-4d4a-bfdd-c4feb1c024a4
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 19.06.2024 15:07:24, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.8.0, Zeitstempel: 0x661e0000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x2aa0
Startzeit der fehlerhaften Anwendung: 0x01dac2496b1faf59
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Kai\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: 3ff1b6ec-3c28-435e-89b3-9f71c6f209bb
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }

**Comment by FatigueDev** [comment]
Changes committed with https://github.com/FatigueDev/typing_indicator/commit/79caea367b3911f6c5522e3df26fc20bbcebffb3. Update to version 1.1.1 and verify, @WickedSchnitzel.

**Comment by FatigueDev** [comment]
Closing as no reply and no mention of this issue in the current build.
